### ISSUE TITLE
Runtime checking of stateless functional components

### ISSUE THREAD

**Issue by jbmusso** [gcanti/prop-types-ts#15]
Greetings. First of all, thank you for making this library which works really great with classes.

I'm trying to type-check stateless functional components defined using `React.SFC<>`:

```typescript
import * as React from 'react';
import * as t from 'io-ts';
import { getPropTypes } from 'prop-types-ts';

const Password = t.refinement(t.string, n => n.length >= 8);

const Login = t.refinement(t.string, s => s.length >= 8);

const Person = t.interface({
  login: Login,
  password: Password,
});

type PersonType = t.TypeOf<typeof Person>;

const PersonBlock: React.SFC<PersonType> = ({ login, password }) => {
  return (
    <div>
      <div>{login}</div>
      <div>{password}</div>
    </div>
  );
};

// Typescript complains here
PersonBlock.propTypes = getPropTypes(Person);

// The following is statically type checked as expected
const App: React.SFC = () => {
  return (
    <div>
      <PersonBlock login="JaneDoe" password={12345678} />
    </div>
  );
};

```

Typescript complains about this line:
`PersonBlock.propTypes = getPropTypes(Person);`

Error:
`Type '{ __prop_types_ts(values: any, prop: string, displayName: string): Error | null; }' is not assignable to type 'ValidationMap<InterfaceOf<{ login: RefinementType<StringType, mixed, string>; password: Refinemen...'.`
`Type '{ __prop_types_ts(values: any, prop: string, displayName: string): Error | null; }' has no properties in common with type 'ValidationMap<InterfaceOf<{login: RefinementType<StringType, mixed, string>; password: Refinemen...'.`

I'm not too familiar with TypeScript. Could you please shed some light on this?

Versions:
```
io-ts@0.9.8
typescript@2.8.1
prop-types-ts@0.6.0
```
(edit: prop-types-ts version)

**Comment by gcanti** [comment]
Looking into the `React` definition file, `PersonBlock.propTypes` is expected to have type `ValidationMap<PersonType>`, i.e. something along the lines of

```ts
{
  login?: (object: PersonType, key: string, componentName: string, ...rest: any[]) => Error | null,
  password?: (object: PersonType, key: string, componentName: string, ...rest: any[]) => Error | null
}
```

however you're passing

```ts
{
  __prop_types_ts(values: any, prop: string, displayName: string): Error | null;
}
```

TypeScript thinks that is likely a bug and complains.

You could either cast to `any`

```ts
PersonBlock.propTypes = getPropTypes(Person) as any
```

or define an helper procedure

```ts
import { PropTypeable } from 'prop-types-ts'

const sfcprops = <T extends PropTypeable>(type: T, f: React.SFC<t.TypeOf<T>>): React.SFC<t.TypeOf<T>> => {
  f.propTypes = getPropTypes(type) as any
  return f
}

const PersonBlock = sfcprops(Person, ({ login, password }) => {
  return (
    <div>
      <div>{login}</div>
      <div>{password}</div>
    </div>
  )
})
```

**Comment by jbmusso** [comment]
This works like a charm, very helpful helper. Thanks for the quick and very instructive answer Giulio.
