### ISSUE TITLE
Introspection of propTypes definition as string. Is this possible?

### ISSUE THREAD

**Issue by sompylasar** [gcanti/prop-types-ts#9]
I'd like to show components' `propTypes` spec in a live styleguide of components. There is no such way in `prop-types` except comparing function references and analyzing return values (errors) of the validator function (which I'm using, but it only works more or less reliable in development build). Is this possible with `prop-types-ts` / `io-ts`? Thank you.

**Comment by gcanti** [comment]
Yes, you can do runtime introspection with `io-ts` types. For example (from the README)

```ts
import * as t from 'io-ts'

const AlertType = t.keyof({
  success: true,
  warning: true,
  info: true
}, 'AlertType')

const RuntimeProps = t.interface({
  type: AlertType
}, 'Props')

console.log(RuntimeProps instanceof t.InterfaceType) // true
console.log(RuntimeProps.props.type instanceof t.KeyofType) // true
console.log(RuntimeProps.props.type.keys) // { success: true, warning: true, info: true }
```

See how the `*Type` (`InterfaceType`, `KeyofType`, `LiteralType`, etc...) classes are defined in `io-ts` for more details

**Comment by sompylasar** [comment]
Awesome, thanks!
